[tool.poetry]
name = "geoloc-imc-2023"
version = "0.1.0"
description = ""
authors = ["hugoRimlinger4 <hugorimlinger4@gmail.com>"]
readme = "README.md"
packages = [{include = "geoloc_imc_2023"}]

[tool.poetry.dependencies]
python = "^3.9,<3.11"
numpy = "^1.21.3"
pandas = "^1.3.4"
matplotlib = "^3.4.3"
plotly = "^5.14.0"
nbformat = "^4.4.0"
seaborn = "^0.12.1"
requests = "^2.28.1"

[tool.poetry.group.dev.dependencies]
ipykernel = "^6.22.0"
flake8 = "^4.0.1"
black = {version = "^23.3.0", allow-prereleases = true}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
